services:
  youtube-playlist-downloader:
    build: .
    container_name: youtube-playlist-downloader
    restart: unless-stopped
    ports:
      - "5006:5006"
    environment:
      - PORT=5006
      - PYTHONUNBUFFERED=1
      - FILE_EXPIRY_SECONDS=7200
    volumes:
      - ./downloads:/app/downloads
